
---
title: "Consumption - SelectInput"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    source_code: embed
    social: menu

runtime: shiny
---


```{r}
library(flexdashboard)
library(tidyverse)
library(plotly)
library(knitr)
library(DT)
df <- read_csv('Consumption.csv')
df$Year = factor(df$Year)  
unique_region <- unique(df$Region)
df$Consumption_2 = ifelse(df$Consumption > median(df$Consumption, na.rm = TRUE), "high", "low")
```

{.sidebar}
=======================================================================

Alcohol consumption has been very popular in Europe. While there was some element different elements in how often and much they drink, it can be seen that certain regions drink different amounts that others.  Select the input for the plots. 

```{r}
selectInput(inputId = "year_input", 
            label = h3("Select Year"),
            choices = unique(df$Year),  # Unique values from the Region column
            selected = unique(df$Year)[1])  # Default to the first region

```

Main Tab 1
=======================================================================

Column {data-width=500}
-----------------------------------------------------------------------

### Density Plot

```{r}
renderPlotly({
  p1 <- df %>% 
    filter(Year == input$year_input) %>%  
    ggplot(aes(x = Liqueurs, color = Year)) +  
    geom_density()  
  ggplotly(p1)  
})

```

Column {data-width=500}
-----------------------------------------------------------------------

### Bar Plot

```{r}
renderPlotly({
  p2 <- df %>% 
    filter(Year == input$year_input) %>% 
    ggplot(aes(x = Beer, y = Wine, color = Consumption_2)) +  
    geom_point()  
  ggplotly(p2) 
})

```
