
---
title: "Consumption - SliderInput"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    source_code: embed
    social: menu

runtime: shiny
---

```{r global, include=FALSE}
# load data in 'global' chunk so it can be shared by all users of the dashboard
library(flexdashboard)
library(tidyverse)
library(plotly)
library(knitr)
library(DT)
df <- read_csv('Consumption.csv')
df <- drop_na(df, Wine)
df$Region = factor(df$Region)
titanic_region <- unique(df$Region)

```

{.sidebar}
=======================================================================

Alcohol consumption has been very popular in Europe. While there was some element different elements in how often and much they drink, it can be seen that certain regions drink different amounts that others.  Select the input for the plots. 

```{r}
sliderInput(inputId = "consumption_input",
            label = h2("Select Consumption Range"),
            min = min(df$Consumption, na.rm=TRUE),
            max = max(df$Consumption, na.rm=TRUE),
            value = c(1, 100))

```

Main Tab 1
=======================================================================

Column {data-width=500}
-----------------------------------------------------------------------

### Density Plot

```{r}
renderPlotly({
  p1 <- df %>% 
    filter(Consumption > input$consumption_input[1], Consumption < input$consumption_input[2]) %>% 
    ggplot(aes(x = Wine, color = Region)) +  
    geom_density()  
  ggplotly(p1)  
})


```

Column {data-width=500}
-----------------------------------------------------------------------

### Bar Plot

```{r}
renderPlotly({
  p2 <- df %>% 
    filter(Consumption > input$consumption_input[1], Consumption < input$consumption_input[2]) %>%  
    ggplot(aes(x = Year, fill = Wine)) +  
    geom_bar() 
  ggplotly(p2)  
})


```
